"""
Django settings for zapateria project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# ================== Rutas base ==================
BASE_DIR = Path(__file__).resolve().parent.parent

# ================== Configuración básica ==================
SECRET_KEY = 'django-insecure-6or3phx)xt1)l37p9*wqeyrfl6tt0rw7voabb_)-un#oi4g8nz'
DEBUG = True
ALLOWED_HOSTS = ['8.222.55.168']

# ================== Aplicaciones instaladas ==================
INSTALLED_APPS = [
    'jazzmin',  # debe estar ANTES de django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',  # tu aplicación
]

# ================== Middleware ==================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zapateria.urls'

# ================== Templates ==================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Carpeta donde están tus plantillas base
        'DIRS': [BASE_DIR / 'app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zapateria.wsgi.application'

# ================== Base de datos ==================
# Si estás usando Docker con PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'zapateria'),
        'USER': os.getenv('POSTGRES_USER', 'zapateria'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'zapateria'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Si prefieres seguir usando SQLite mientras tanto, comenta el bloque anterior
# y descomenta este:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# ================== Validación de contraseñas ==================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'app.validators.MinimumLengthValidator',
        'OPTIONS': {'min_length': 16}
    },
    {
        'NAME': 'app.validators.UppercaseValidator',
    },
    {
        'NAME': 'app.validators.DigitValidator',
    },
    {
        'NAME': 'app.validators.SymbolValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
]

# ================== Internacionalización ==================
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Guatemala'
USE_I18N = True
USE_TZ = True

# ================== Archivos estáticos ==================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'statics']

# ================== Archivos multimedia (opcional) ==================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ================== Autenticación ==================
LOGIN_REDIRECT_URL = 'store'
LOGOUT_REDIRECT_URL = 'store'
LOGIN_URL = 'login'  # si intentan acceder al checkout sin estar logueados

# ================== Campo por defecto ==================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Agrega al final de settings.py
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desarrollo
DEFAULT_FROM_EMAIL = 'noreply@zapateria.com'

# Para producción (configura estos valores)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_password'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'zapateriagkicks@gmail.com'  
EMAIL_HOST_PASSWORD = 'tqcj fkeb tzmd qkxa'  
DEFAULT_FROM_EMAIL = 'zapateriagkicks@gmail.com'

# Protección contra ataques de fuerza bruta
#AUTHENTICATION_BACKENDS = [
 #   'django.contrib.auth.backends.ModelBackend',
#]

# Configuración de intentos de login
AXES_ENABLED = True  # Si instalas django-axes

# ================== Configuración de Jazzmin ==================
JAZZMIN_SETTINGS = {
    # Título de la ventana (aparecerá en la pestaña del navegador)
    "site_title": "Zapatería Admin",

    # Título en el login
    "site_header": "Zapatería",

    # Título en la página principal del admin
    "site_brand": "Zapatería Store",

    # Logo para usar en modo claro (sidebar)
    "site_logo": None,

    # Logo para el navbar
    "login_logo": None,

    # Logo para el login
    "login_logo_dark": None,

    # CSS personalizado
    "site_logo_classes": "img-circle",

    # Icono para el sitio (favicon)
    "site_icon": None,

    # Mensaje de bienvenida en la pantalla de login
    "welcome_sign": "Bienvenido a Zapatería Admin",

    # Copyright en el footer
    "copyright": "Zapatería Store",

    # Usuario en el navbar
    "search_model": ["auth.User", "app.Product", "app.Customer", "app.Order"],

    # Campo del usuario para mostrar
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links adicionales para mostrar en el top menu
    "topmenu_links": [
        # URL que se abrirá en una nueva pestaña
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Sitio", "url": "/", "new_window": True},
        {"model": "auth.User"},
        {"app": "app"},
    ],

    #############
    # User Menu #
    #############

    # Links adicionales para incluir en el menú de usuario
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Si mostrar el menú lateral
    "show_sidebar": True,

    # Si el menú lateral debe comenzar expandido
    "navigation_expanded": True,

    # Ocultar aplicaciones que coincidan con estos nombres
    "hide_apps": [],

    # Ocultar modelos que coincidan con estos nombres
    "hide_models": [],

    # Orden de las aplicaciones y modelos en el menú lateral
    "order_with_respect_to": ["auth", "app"],

    # Iconos personalizados para cada app/modelo
    # Puedes usar iconos de Font Awesome 5
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.Customer": "fas fa-user-circle",
        "app.Product": "fas fa-shoe-prints",
        "app.Order": "fas fa-shopping-cart",
        "app.OrderItem": "fas fa-list",
        "app.ShippingAddress": "fas fa-truck",
    },

    # Iconos por defecto para modelos sin icono específico
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################

    # Usar modals para las relaciones
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############

    # Temas relativos al esquema de colores
    # "default", "cerulean", "cosmo", "cyborg", "darkly", "flatly", "journal",
    # "litera", "lumen", "lux", "materia", "minty", "pulse", "sandstone",
    # "simplex", "slate", "solar", "spacelab", "superhero", "united", "yeti"
    "theme": "darkly",

    # Tema oscuro (si está disponible)
    "dark_mode_theme": "darkly",

    # Botón para cambiar entre tema claro y oscuro
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############

    # Renderizar la vista de cambio como una sola columna
    "changeform_format": "horizontal_tabs",

    # Anular los estilos con CSS personalizado
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },

    # Agregar un botón de acción personalizado al menú lateral
    "custom_links": {
        "app": [{
            "name": "Reportes",
            "url": "admin:index",
            "icon": "fas fa-chart-line",
            "permissions": ["app.view_order"]
        }]
    },
}

# UI Tweaks adicionales
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}